### ISSUE TITLE
コメント編集時の通知を止めたい

### ISSUE THREAD

**Issue by takanamito** [kotatsu360/gomashio#5]
# 要望
issue/PRのコメントでwebhookアクションの`edited`にあたるイベントの通知を止められるようにしたい。
通知をするアクションの設定ができると汎用的で便利だと思います。
https://developer.github.com/v3/activity/events/types/#issuecommentevent

# ユースケース
slackに `edited`アクションに該当する通知が流れてくることで
同じような見た目の通知が大量に飛んでくることを防ぎたい。
(長めの文章を書いたコメントの最後尾に追記する場合、コメントの前半は変更されてないので同じ文章の通知がたくさん飛んでくる)

**Comment by kotatsu360** [comment]
issueありがとうございます。確認します。

**Comment by kotatsu360** [comment]
@takanamito 
configで非通知にしたいイベントを設定できるようにしました。

Thank you post issue.

New Config Attribute `ignore_event_map`.
You can set the event you want not to notify in config.

**Comment by takanamito** [comment]
Thank you!! 🎉
